[openai]
api_key = "your-openai-key"
# Choose model_name between gpt-4, gpt-3.5-turbo
model_name = "gpt-4"
temperature = 0.5

[books]
favorites = """
Project Hail Mary, Andy Weir
Home Before Dark, Riley Sager
The Invisible Life of Addie LaRue, V.E. Schwab
"""

